# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alonewell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellbasicdata',
            name='wellName',
            field=models.CharField(max_length=40),
        ),
    ]
