# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alonewell', '0002_auto_20170429_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WellBasicData',
        ),
    ]
