# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alonewell', '0003_delete_wellbasicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellBasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellNo', models.IntegerField()),
                ('wellName', models.CharField(max_length=40)),
                ('dimension', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
