# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alonewell', '0004_wellbasicdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellbasicdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='wellbasicdata',
            name='wellNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
