# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alonewell', '0008_auto_20170710_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellbasicdata',
            options={'permissions': (('test1_wellbasicdata', 'this is test for permissions'), ('test2_wellbasicdata', 'this is test for permissions'), ('test3_wellbasicdata', 'this is test for permissions'))},
        ),
    ]
